feat: endpoint schemas for accesssing websites
GymSquad/archive-api pull request #3
Opened 2024-01-21 13:28 UTC by alan910127

2024-01-21 13:29 UTC, alan910127 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/GymSquad/archive-api/3?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1** <a href="https://app.graphite.dev/github/pr/GymSquad/archive-api/1?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #3** <a href="https://app.graphite.dev/github/pr/GymSquad/archive-api/3?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/GymSquad/archive-api/3?utm_source=stack-comment).

2024-01-22 15:40 UTC, BaBa0525 commented on app/websites/schemas.py
> +    }
好像怪怪的 0.0

2024-01-22 15:45 UTC, BaBa0525 requested changes
試試看

2024-01-27 08:05 UTC, BaBa0525 approved these changes
<img src="https://media1.giphy.com/media/qnWjDNWHm9Wy1zLwG8/giphy.gif"/>

2024-01-27 11:16 UTC, alan910127 commented
### Merge activity

* **Jan 27, 6:16 AM**: @alan910127 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/GymSquad/archive-api/3).

2024-01-27 11:18 UTC, merged